version: "3.3"

services:
  proxy:
    container_name: proxy
    restart: always
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./webconf/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./webconf/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./webconf/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx:rw
  server:
    container_name: taxi-server
    restart: always
    image: tklco/taxi-server:latest
    depends_on:
      - db
    environment:
      - PORT=80
      - DB_PATH=mongodb://db:27017/taxi
      - REDIS_HOST=redis://redis:6379
      - SPARCSSSO_CLIENT_ID=${SPARCSSSO_CLIENT_ID}
      - SPARCSSSO_CLIENT_KEY=${SPARCSSSO_CLIENT_KEY}
      - FRONT_URL=${FRONT_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - SESSION_KEY=${SESSION_KEY}
    networks:
      - taxi-net
  client:
    container_name: taxi-client
    restart: always
    image: tklco/taxi-client:latest
    environment:
      - REACT_APP_BACK_URL=${REACT_APP_BACK_URL}
      - REACT_APP_S3_URL=${REACT_APP_S3_URL}
  db:
    container_name: db
    restart: always
    image: mongo:5.0.8
    volumes:
      - mongo-logs:/var/log/mongodb:rw
      - mongo-data:/var/lib/mongodb:rw
      - ./mongodb.conf:/etc/mongo/mongodb.conf:ro
    networks:
      - taxi-net
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    networks:
      - taxi-net
  db_backup:
    container_name: db_backup
    restart: always
    build: ./db_backup
    command: 
    volumes:
      - ./backup:/backup:rw

volumes:
  mongo-logs:
  mongo-data:

networks:
  taxi-net:


