name: Push Server and Client images to Docker Hub
on: [push, pull_request]


jobs:
  build:
    name: Push Server and Client images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Server image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/taxi-server:latest
      - name: Build and push Client image
        uses: docker/build-push-action@v1
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/taxi-client:latest
  restart_server:
    name: Restart Server with New Image
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /app/taxi/
            ./setup.sh